spring.application.name=bananaapp
#server.port=8888
shinhan.api.key=${SHINHAN_API_KEY}
spring.profiles.active=dev,maria

#level : TRACE > DEBUG > INFO > WARN > ERROR
logging.level.root= INFO
#logging.level.com.shinhan.bananaapp=INFO
logging.level.org.springframework.web= INFO
logging.pattern.console=%clr(%-5level){green} %clr(%logger.%M\\(\\)){blue}: %msg%n
