spring.application.name=bananaapp
#server.port=8888
spring.profiles.active=dev

#level : TRACE > DEBUG > INFO > WARN > ERROR
logging.level.root= INFO
logging.level.org.springframework.web= INFO
logging.pattern.console=%clr(%-5level){green} %clr(%logger.%M\\(\\)){blue}: %msg%n

