spring.application.name=bananaapp
#server.port=8888
shinhan.api.key=1234
spring.profiles.active=dev,maria,mybatis,jpa

#level : TRACE > DEBUG > INFO > WARN > ERROR
logging.level.root= INFO
#logging.level.com.shinhan.bananaapp=INFO
logging.level.org.springframework.web= INFO
logging.pattern.console=%clr(%-5level){green} %clr(%logger.%M\\(\\)){blue}: %msg%n

