spring:
  jpa:
    hibernate:
      # create: 기존 테이블 삭제 후 생성 / update: 변경 부분만 반영
      # validate: 매핑 검증만 / none: 아무것도 안 함
      # 운영에서는 반드시 validate 또는 none!
      ddl-auto: update
    show-sql: true                          # 실행시 SQL 콘솔 출력, 운영환경은 false
    properties:
      hibernate:
        format_sql: true                    # SQL 포맷팅(가독성 개선)
    defer-datasource-initialization: true   # ←  JPA 초기화 완료 후 SQL 실행하도록 순서 보장

  batch:
    job:
      enabled: false      # 서버 시작 시 자동 실행 방지
    jdbc:
      initialize-schema: never # 배치 메타 테이블 자동 생성 : always , 자동 생성 x : never , 이미있을시 자동생성하면 경고만 뜸
  sql:
    init:
      mode: always
