# HS256 알고리즘 — 최소 256bit(32byte) 키 필요
# JWT 서명(Signature)을 만들 때 사용하는 비밀키
jwt.secret=ZrVY5FQpQb4u2u4f1z9Y6pX+q9hJ8+e0H7X0R3EJkNc=

# Access Token 만료: 20분
jwt.expiration_minute=20

# Refresh Token 만료: 7일 ....저장방법1 : DB저장 , 저장방법2 : Redis 사용
jwt.refresh_expiration_day=7

