shinhan:
  api1:
    key1: 1234
    key2: abcd
  api2:
    key1: 5555
    key2: kang
  api3: ${SHINHAN_API_KEY}

#default로 설정됨 templates 밑에 저장이 된다
#spring:
#  thymeleaf:
#    prefix: classpath:/templates/   # 탐색 경로
#    suffix: .html                    # 확장자
#    cache: false                    # 개발 중 캐시 끄기 (devtools 있으면 자동)
#    encoding: UTF-8

springdoc:
  swagger-ui:
    path: /swagger-ui.html   # Swagger UI 접근 경로
    tags-sorter: alpha        # 태그 알파벳 정렬
  api-docs:
    path: /api-docs           # OpenAPI JSON 경로


server:
  port: 8000