spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/shinhandb7
    username: shinhanuser
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10      # 최대 커넥션 수
      minimum-idle: 5            # 최소 유지 커넥션
      connection-timeout: 30000  # 커넥션 획득 대기 시간(ms)
      idle-timeout: 600000       # 유휴 커넥션 유지 시간(ms)